### ISSUE TITLE
some error on mining

### ISSUE THREAD

**Issue by moodsj** [FACT0RN/FACT0RN#22]
when i exec this command  python FACTOR.py <scriptPubKey>
some error happen on it :
  
        ***   Warning: new maximum stack size = 536870912 (512.000 Mbytes).
Traceback (most recent call last):
  File "FACTOR.py", line 629, in <module>
    gHash = ctypes.CDLL("./gHash.so").gHash
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./gHash.so: cannot open shared object file: No such file or directory

gHash.so file not found, how can i fix this issues？

**Comment by daedalus** [comment]
Yo need to compile it with build.sh

**Comment by ReverseControl** [comment]
As @daedalus pointed out you need to build it with the ``build.sh`` script. I added instructions this morning for it on the mining repo for FACT0RN.
