### ISSUE TITLE
possibly undefined macros during autogen.sh

### ISSUE THREAD

**Issue by Calebtheaa** [FACT0RN/FACT0RN#31]
When I ran autogen.sh after building the depends, I got an error from a few "possibly undefined" macros. It suggested to include m4_pattern_allow, so I added the command into the file. When I ran it again, I got another error, saying that configure.ac is required. Even when resetting everything but depends back before I ran it for the first time, I still got the error. I have no idea why this is happening, but there seems to be no workaround to it.

Here's the errors:
with m4_pattern_allow:
![image](https://github.com/FACT0RN/FACT0RN/assets/90156844/8f0ea57d-eae9-4c26-af2d-328bfca04c5a)
without m4_pattern_allow:
![image](https://github.com/FACT0RN/FACT0RN/assets/90156844/a03abba4-2beb-4c84-9c65-5310cbe9741c)

I'm using the Debian distro with amd x64. This OS is being ran on an OracleVM virtual machine.

**Comment by Calebtheaa** [comment]
iirc, I'm using version 12 (Bookworm).

**Comment by ReverseControl** [comment]
Do you have installed the latest versions of: ``pkg-config libtool``? Historically this is usually the issue with undefined macros and configure.ac.

**Comment by Calebtheaa** [comment]
It appears that reinstalling pkg-config has solved the problem. Thanks for
the help!

**Comment by ReverseControl** [comment]
Sure.
